### ISSUE TITLE
update go-win32-utils dep

### ISSUE THREAD

**Issue by umbynos** [arduino/arduino-cloud-cli#110]
This bindings have been added to [golang updream](https://pkg.go.dev/golang.org/x/sys/windows#KnownFolderPath), so the lib https://github.com/arduino/go-win32-utils has to be removed as a dep and the repo archived.
Related to https://github.com/arduino/arduino-language-server/issues/134 and https://github.com/arduino/arduino-cli/issues/1835

**Comment by cmaglie** [comment]
Actually, we decided to not remove the library, but to refactor it and made use of go.mod.
So just updating the library is fine.
